services:
  - type: web
    name: spesfidem-video-server
    env: node
    rootDir: consultoria-app/backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    repo: https://github.com/espinosagarciajhonedinson-droid/spesfidem_aluminio
    branch: master
    envVars:
      - key: NODE_ENV
        value: production
